In [12]:
import pandas as pd 
import zipfile
name="online+retail.zip"
with zipfile.ZipFile(name,'r') as asww:
     m=asww.namelist()
     print(m)
     with asww.open(m[0]) as op:
        df=pd.read_excel(op)
df.head()

['Online Retail.xlsx']

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [23]:
import pymysql
from sqlalchemy import create_engine
engine=create_engine('mysql+pymysql://root:password@localhost:3306/sales_db')
df.to_sql("rawsales",con=engine,if_exists='replace',index=False)

541909

In [24]:
pd.read_sql("SELECT * FROM sales_db.rawsales LIMIT 5",con=engine)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [9]:
import pandas as pd
from sqlalchemy import create_engine
import pymysql
engine=create_engine('mysql+pymysql://root:password@localhost:3306/sales_db')
sqlquery="SELECT * FROM rawsales where Country= 'France'and Quantity>30 limit 5000"
ac=pd.read_sql(sqlquery,con=engine)
ac.to_excel("final.xlsx",index=False)